apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ratings-producer
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: ratings-producer
  endpoints:
  - port: metrics